// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace DermPOCAppML.Model
{
    public class ModelOutput
    {
        [ColumnName("PredictedLabel")]
        public String Prediction { get; set; }

        [ColumnName("Score")]
        public float[] Score { get; set; }
    }
}
